export const LANDPAGE = '/'
export const DASHBOARD = '/home'
export const LOGIN = '/signin'
export const SIGNUP = '/signup'
export const PROFILE = '/p'
export const SETTING = '/edit'
export const NOT_FOUND = '/not-found'